### ISSUE TITLE
[Tracking] w3up phase 3

### ISSUE THREAD

**Issue by heyjay44** [storacha/w3up#221]
# DAG House – w3up MVP for March 17

**Milestones**: 
1. w3up demo series for PL
2. associated blog posts highlighting the latest and greatest
3. ability to start user migration

🔴 P0 🟡 P1 🟢 P2

## 🔴 w3access + w3provider + w3session

- [ ] [w3provider](https://github.com/web3-storage/specs/blob/main/w3-provider.md) (MVP free tier provider)
    - [ ] [w3protocol#347](https://github.com/web3-storage/w3protocol/issues/347) Email template improvements - @travis 
            ^ MOVED here: https://github.com/web3-storage/w3protocol/issues/650 Finish implementing
    - [x] [w3protocol#348](https://github.com/web3-storage/w3protocol/issues/348) GET -> POST on email validation links - @travis
    - [x] [w3protocol#341](https://github.com/web3-storage/w3protocol/issues/341) Postmark daghouse domain move to web3.storage - @travis
- [x] Finish implementing [w3access](https://github.com/web3-storage/specs/blob/main/w3-access.md)
    - (Sharing delegations across agents/devices)
    - [x] [w3protocol#393](https://github.com/web3-storage/w3protocol/issues/393) `access/delegate` - @gobengo 
    - [x] [w3protocol#394](https://github.com/web3-storage/w3protocol/issues/394) `access/claim` - @gobengo 
    - [x] [w3protocol#395](https://github.com/web3-storage/w3protocol/issues/395) (w3access & w3session in client) - @gozala, @alanshaw, @travis, @gobengo  
- [x] Finish implementing [w3session](https://github.com/web3-storage/specs/blob/main/w3-session.md) @gozala
    - [x] (Verification via email and did:mailto usage)https://github.com/web3-storage/ucanto/pull/227
    - [x] update [session spec](https://github.com/web3-storage/specs/blob/main/w3-session.md) to reflect [227](https://github.com/web3-storage/ucanto/pull/227) https://github.com/web3-storage/ucanto/issues/228
    - [x] update ucanto
    - [x] [w3protocol#293](https://github.com/web3-storage/w3protocol/issues/293) Fix the delegation over websocket slowness - @travis
- [x] [w3protocol#384](https://github.com/web3-storage/w3protocol/issues/384) Finish single URL for web3.storage Ucanto - @gobengo 
- [x] https://github.com/web3-storage/w3protocol/issues/344 (blocking w3ui testing)

- [x] Upgrade upload-api to ucanto5, make sure space verification works still @Gozala 
- [x] Make space verification better, space/info returns provider info @gobengo 
- [x] Propagate access/account changes to access.agent -> w3up-client -> w3cli and w3ui and w3console
- [ ] https://github.com/web3-storage/w3protocol/issues/520
        ^ MOVED here: https://github.com/web3-storage/w3protocol/issues/650
- [x] accounts/email for account recovery

## 🔴 Turn off clusters

- [ ] [backup#1](https://github.com/web3-storage/backup/issues/1) Migrate data
    - [x] make (new) list of CIDs to migrate for web3.storage – @alanshaw
    - [ ] complete web3.storage cluster migration 
         ^ moved here: https://github.com/web3-storage/w3protocol/issues/650
    - [ ] complete nft.storage cluster migration 
         ^ moved here: https://github.com/web3-storage/w3protocol/issues/650
- [ ] [pickup#68](https://github.com/web3-storage/pickup/issues/68) Rollout pickup
    - [x] migrate web3.storage pinning services to pickup (current: 100% traffic) - @olizilla 
    - [x] migrate nft.storage pinning services to pickup (current: 100% traffic) - @olizilla 
- [ ] Inform netops when safe to decommission
        ^ moved here: https://github.com/web3-storage/w3protocol/issues/650

## 🟡 w3s.link + nftstorage.link gateways

- [x] decrease R2 operations - @vasco-santos [web3-storage/freeway#24](https://github.com/web3-storage/freeway/pull/24), [nftstorage/nft.storage#2331](https://github.com/nftstorage/nft.storage/pull/2331), [web3-storage/web3.storage#2227](https://github.com/web3-storage/web3.storage/pull/2227)
- [x] remove upstream CF gateway (save $) - @vasco-santos https://github.com/web3-storage/reads/pull/142
- [x] remove upstream pinata gateway (save $) - @vasco-santos https://github.com/web3-storage/reads/pull/142
- [x] redirect back to dweb.link for content not available in freeway^ - @vasco-santos  https://github.com/web3-storage/reads/pull/142
- [ ] Q: Can we turn on gzip and save some bandwidth? - @olizilla + @vasco-santos 
         ^ moved here: https://github.com/web3-storage/w3protocol/issues/650

### Notes

This would reduce proxied traffic significantly... CF is charging us for egress of content we're not storing.

## 🟡 Elastic IPFS costs

- [ ] Verify blake2b fix is cause of increased egress - @alanshaw 
- [x] [Research solutions for reducing costs](https://www.notion.so/E-IPFS-ideas-for-other-improvements-0c287433c50749d0bab22d6feecfbe03) - @vasco-santos 
     - document low hanging fruit and implement changes to reduce costs
          - [x] https://github.com/elastic-ipfs/indexer-lambda/pull/72
- [x] Reduce write operations to dynamoDB - @vasco-santos https://github.com/elastic-ipfs/indexer-lambda/pull/72
- [x] Implement bitswap cancel handling - @vasco-santos https://github.com/elastic-ipfs/bitswap-peer/pull/193

### Notes

Seeing sustained increase since jan
- egress costs
- dyanmo costs from indexing per block

## 🟡 w3up Metrics

- [x] Kinesis consumers for tracking https://github.com/web3-storage/w3infra/issues/117 - @vasco-santos:
* User facing aggregations 
	* [x] Space upload/add counter - https://github.com/web3-storage/w3infra/pull/118
	* [x] Space store/add counter - https://github.com/web3-storage/w3infra/pull/160
	* [x] Space store/remove counter - https://github.com/web3-storage/w3infra/pull/160
	* [x] Space store/add size sum - https://github.com/web3-storage/w3infra/pull/164
	* [x] Space store/remove size sum - https://github.com/web3-storage/w3infra/pull/164
	* [x] Space upload/remove counter - https://github.com/web3-storage/w3infra/pull/163
* System wide metrics
	* [x] Total storage committed => `store/add size` https://github.com/web3-storage/w3infra/pull/146
	* [x] Total number of CARs stored  => `store/add count` https://github.com/web3-storage/w3infra/pull/151
	* [x] Total number of CARs removed  => `store/remove count` https://github.com/web3-storage/w3infra/pull/151
	* [x] Total number of uploads removed => `upload/remove count` https://github.com/web3-storage/w3infra/pull/157
	* [x] Total number of uploads => `upload/add count` https://github.com/web3-storage/w3infra/pull/162
	* [x] Total storage uncommited => `store/remove + receipt from system` ? https://github.com/web3-storage/w3infra/pull/158
* Metrics visualization
	* [x] HTTP Endpoint  https://github.com/web3-storage/w3infra/pull/156
	* [x] Prometheus https://github.com/web3-storage/telemetry-grafana-agent/pull/3
	* [x] Grafana dashboard
- [x] UCAN LOG Stream Kinesis gateway for other services (access-api, ...) - @vasco-santos 
- [ ] integrate Redshift as Kinesis consumer - @vasco-santos 
- [ ] Kinesis to emit events when there are 32 GB deals (as a placeholder, for now, call a function that does nothing)

Once above is completed, then tackle:
- [x] Integrate Prometheus like API + Grafana - @vasco-santos https://github.com/web3-storage/w3infra/issues/147
    - [x] decide what Grafana instance to use
    - [ ] usage over time??
           ^ MOVED here: https://github.com/web3-storage/w3protocol/issues/650
- [ ] Figure out how to extract NFT.Storage specific metrics
       ^ MOVED here: https://github.com/web3-storage/w3protocol/issues/650

### Notes

Docs:

* https://www.notion.so/DS9-Q1-metrics-goals-41b617591d8e4f7fb5bae94f655d6c82
* [2023-02-02 meeting notes](https://www.notion.so/2023-02-02-metrics-MVP-sync-3b939213b45046368980a9d8dd7cb7bc)
* [Draft of product requirements](https://www.notion.so/UCAN-metrics-Requirements-Document-c4abe1951076459284af3928de4a6800)

## 🟡 Specifications

- [ ] Tweaks on specification for [store/upload protocol](https://github.com/web3-storage/specs/blob/main/w3-store.md) @gozala
    - Reads like blog/how-to - needs more formal
- [ ] Specify expected invocation responses

## 🟢 w3ui/console
- [x] https://github.com/web3-storage/w3protocol/issues/494
- [x] https://github.com/web3-storage/w3protocol/issues/487
- [x] identify bugs/quirks in current iteration of console
- [x] [w3ui#142](https://github.com/web3-storage/w3ui/issues/142) w3console design - @plwileverts 
     - Update: we are reducing the scope of work by removing the customisable components for now. This makes the initial design 
     easier and overall maintenance less burdensome. 
    - requirements [here](https://www.notion.so/February-2023-w3ui-Design-Refresh-bddf6a61d61c4a14bfb63081ffed730f)
- [ ] [w3ui#378](https://github.com/web3-storage/w3ui/issues/378) upload progress reporting (fix upload-client, w3up-client, headless components) - @travis
       ^ MOVED here: https://github.com/web3-storage/w3protocol/issues/650
- [x] consider what is essential for deploying beta console site
- [x] https://github.com/web3-storage/w3infra/pull/144
- [x] deploy console for nft.storage and web3.storage to separate domains 

## 🟢 w3filecoin

- [x] Align on dagcargo for previous system - @vasco-santos 
- [ ] [w3protocol#353](https://github.com/web3-storage/w3protocol/issues/353) CommP in client - @gozala @vasco-santos 
- [ ] Consumer stack - add CAR CIDs to w3filecoin pipe after store/add [w3filecoin#12](https://github.com/web3-storage/w3filecoin/issues/12) - @vasco-santos
- [ ] Wire dead letter queues [w3filecoin#10](https://github.com/web3-storage/w3filecoin/issues/10) - @vasco-santos 

### Notes

Filecoin integration is a big missing piece!

These tasks are **Blocked on spade**:

- spade write integration - https://github.com/web3-storage/w3filecoin/issues/14
- spade deal success check / retry?
- (not) spade read integration - find deals my CID is in. https://github.com/web3-storage/w3filecoin/issues/15
- metrics -  https://github.com/web3-storage/w3filecoin/issues/13

## 🟢 Demos 
- [ ] Demo series advocating for the w3up stack @dchoi27 @alanshaw 

## 🟢 Sharding
- [ ] Add UnixFS directory sharding [w3up-client#54](https://github.com/web3-storage/w3up-client/issues/54)
     - [ ] ensure that other implementations can read it but don't worry about overall compliance yet
- [ ] Add support for HAMT directories [ipld/js-unixfs#37](https://github.com/ipld/js-unixfs/issues/37) (this is not on the board as @heyjay44 doesn't have permissions to add to a project)

## 🟢 Checkup

- [ ] [checkup#3](https://github.com/nftstorage/checkup/issues/3) Update checkup to consider data in new S3 buckets - @alanshaw @vasco-santos 

## 🟢 differentiating uploads
- [ ] differentiate between nft and web3 dot storage uploads

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

---

# A future phase!

## Receipts (deprioritized)

We are invested in this. It's WIP. We should land it. it's:
- on critical path for billing.
- on critical for metrics (currently, we could calculate in other way)

_what is the minimal receipts flow?_

we need to tightly define what success of this endevour looks like

- finish off work to land it ucanto
- do work work to integrate it into store/add and s3 ObjectCreated

## w3provider (deprioritized)

- [ ] [w3protocol#349](https://github.com/web3-storage/w3protocol/issues/349) `provider/get` `consumer/add`
- [ ] [w3protocol#350](https://github.com/web3-storage/w3protocol/issues/350) `provider/add`

## Others

- Publicly verifiable timestamps for UCAN invocations [web3-storage/specs#27](https://github.com/web3-storage/specs/pull/27)
- CAR retrieval by CAR CID [w3protocol#274](https://github.com/web3-storage/w3protocol/issues/274)

## Notes

^gateway: total cost of serving old content may be higher if we bounce the user to dweb.link and it then has to fetch it from e-ipfs, but we should just go for it and monitor. if freeway doesn't have it then currently we pay twice as ipfs.io serves it to w3s.link.

migration off old api: ???

### Tech debt

- validate CIDs for blocks in CARs - previously cluster was our validator. we don't have a replacement yet.

### Questions

what's costing us the most right now?
- CDN data transfer in Cloudflare (not clear, but everything that leaves CF's network.)
